export const GET_COMMENTS_SAGA = "GET_COMMENTS_SAGA";
export const GET_COMMENTS = "GET_COMMENTS";
export const DELETE_COMMENT_SAGA = "DELETE_COMMENT_SAGA";
export const UPDATE_COMMENT_SAGA = "UPDATE_COMMENT_SAGA";
export const INSERT_COMMENT_SAGA = "INSERT_COMMENT_SAGA";
