export const USER_SIGIN_API = "USER_SIGNIN_SAGA";
export const GET_TASK_API = "GET_TASK_API";
export const DISPLAY_LOADING = "DISPLAY_LOADING";
export const HIDE_LOADING = "HIDE_LOADING";
//get project category
export const GET_ALL_PROJECT_CATEGORY_SAGA = "GET_ALL_PROJECT_CATEGORY_SAGA";
export const GET_ALL_PROJECT_CATEGORY = "GET_ALL_PROJECT_CATEGORY";
